INSERT INTO STORAGE(HEIGHT, WIDTH, DEPTH)
VALUES (10.1, 10.4, 10.2);
INSERT INTO STORAGE(HEIGHT, WIDTH, DEPTH)
VALUES (15.2, 2.0, 22.7);
INSERT INTO STORAGE(HEIGHT, WIDTH, DEPTH)
VALUES (12.3, 31.8, 1.0);

INSERT INTO VEHICLE(VEHICLE_ID, LOADING_TIME, DISCHARGE_TIME, STORAGE_ID, LOAD_FACTOR, BLOCKED)
VALUES ('FAHRZEUGKENNUNG 1', 10, 20, 1, 3.1, false);
INSERT INTO VEHICLE(VEHICLE_ID, LOADING_TIME, DISCHARGE_TIME, STORAGE_ID, LOAD_FACTOR, BLOCKED)
VALUES ('FAHRZEUGKENNUNG 2', 3, 30, 2, 5.5, false);
INSERT INTO VEHICLE(VEHICLE_ID, LOADING_TIME, DISCHARGE_TIME, STORAGE_ID, LOAD_FACTOR, BLOCKED)
VALUES ('FAHRZEUGKENNUNG 3', 30, 2, 3, 8, true);