CREATE TABLE STORAGE
(
    ID     INTEGER NOT NULL AUTO_INCREMENT,
    HEIGHT  DOUBLE  NOT NULL,
    WIDTH DOUBLE  NOT NULL,
    DEPTH  DOUBLE  NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE VEHICLE
(
    ID              INTEGER      NOT NULL AUTO_INCREMENT,
    VEHICLE_ID VARCHAR2(64) NOT NULL,
    LOADING_TIME      INTEGER NOT NULL,
    DISCHARGE_TIME     INTEGER NOT NULL,
    STORAGE_ID     INTEGER NOT NULL,
    LOAD_FACTOR        DOUBLE  NOT NULL,
    BLOCKED       BOOLEAN NOT NULL,
    PRIMARY KEY (ID),

    CONSTRAINT FK_STORAGE
        FOREIGN KEY (STORAGE_ID)
            REFERENCES STORAGE (ID)
);
