CREATE TABLE LADERAUM
(
    ID     INTEGER NOT NULL AUTO_INCREMENT,
    HOEHE  DOUBLE  NOT NULL,
    BREITE DOUBLE  NOT NULL,
    TIEFE  DOUBLE  NOT NULL,
    PRIMARY KEY (ID)
);


CREATE TABLE FAHRZEUG
(
    ID              INTEGER      NOT NULL AUTO_INCREMENT,
    FAHRZEUGKENNUNG VARCHAR2(64) NOT NULL,
    BELADEZEIT      INTEGER,
    ENTLADEZEIT     INTEGER,
    LADERAUM_ID     INTEGER,
    BELEGUNG        VARCHAR2(16),
    BLOCKIERT       BOOLEAN,
    PRIMARY KEY (ID),

    CONSTRAINT FK_LADERAUM
        FOREIGN KEY (LADERAUM_ID)
            REFERENCES LADERAUM (ID)
);
